# Generated by Django 5.1.2 on 2025-02-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_rename_description_task_course_task_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Assignment",
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("no_status", "No Status"),
                ],
                default="no_status",
                max_length=20,
            ),
        ),
    ]
