# Generated by Django 5.1.2 on 2025-02-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_delete_assignment_task_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="course",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(blank=True),
        ),
    ]
