# Generated by Django 5.1.2 on 2025-03-08 17:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_alter_task_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="managebac",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="time_estimation",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
