# Generated by Django 5.1.2 on 2025-03-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_task_managebac_task_time_estimation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="time_estimation",
            field=models.DurationField(
                help_text="Estimated time to complete the task (e.g., 2:30:00 for 2 hours 30 minutes)"
            ),
        ),
    ]
