# Generated by Django 5.1.2 on 2025-03-08 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_alter_task_time_estimation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="time_estimation",
            new_name="time_estimate",
        ),
    ]
