# Generated by Django 5.1.2 on 2025-03-08 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0010_rename_time_estimation_task_time_estimate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="time_estimate",
        ),
    ]
