# Generated by Django 5.1.2 on 2025-03-08 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0011_remove_task_time_estimate"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="time_estimate",
            field=models.DurationField(
                default=datetime.timedelta(0),
                help_text="Estimated time to complete the task (e.g., 2:30:00 for 2 hours 30 minutes)",
            ),
        ),
    ]
