# Generated by Django 5.1.8 on 2025-04-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_task_time_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source_id',
            field=models.CharField(blank=True, help_text='External ID from the source system', max_length=100, null=True),
        ),
    ]
