# Generated by Django 5.1.8 on 2025-04-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_task_source_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='managebac',
        ),
        migrations.AddField(
            model_name='task',
            name='reasoning',
            field=models.TextField(blank=True),
        ),
    ]
