# Generated by Django 5.1.8 on 2025-04-07 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_subtask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={},
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='order',
        ),
    ]
