# Generated by Django 5.1.8 on 2025-04-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_subtask_options_remove_subtask_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='importance',
        ),
        migrations.AddField(
            model_name='task',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
