# Generated by Django 5.1.8 on 2025-04-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_remove_task_importance_task_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
