# Generated by Django 5.1.8 on 2025-04-08 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_subtask_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='actual_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), help_text='Actual time spent on the subtask (e.g., 0:45:00 for 45 minutes)', null=True),
        ),
    ]
